import type { Metadata } from "next";
import { Figtree } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["500", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${figtree.variable}`}>{children}</body>
    </html>
  );
}
